/**
 * 古河市 観光スポットデータ
 *
 * 座標はおおよその位置です。実運用の際は現地で正確な座標を測定し、
 * radius(チェックイン許容半径・メートル)とあわせて調整してください。
 * keyword は現地掲示を想定した「合言葉」チェックイン用です。
 */
const SPOTS = [
  {
    id: "rekihaku",
    name: "古河歴史博物館",
    kana: "こがれきしはくぶつかん",
    category: "歴史・文化",
    emoji: "🏛️",
    color: "#8d4a2f",
    lat: 36.19115,
    lng: 139.69760,
    radius: 300,
    keyword: "ゆきのはな",
    address: "古河市中央町3-10-56",
    description:
      "古河藩家老・鷹見泉石の蘭学資料や古河の歴史を紹介する博物館。雪の結晶を意匠にした「雪華模様」ゆかりの地としても有名。",
    hours: "9:00〜17:00（入館は16:30まで）",
    holiday: "月曜・第4金曜・年末年始",
  },
  {
    id: "takamisenseki",
    name: "鷹見泉石記念館",
    kana: "たかみせんせききねんかん",
    category: "歴史・文化",
    emoji: "🏯",
    color: "#5b6e3a",
    lat: 36.19070,
    lng: 139.69680,
    radius: 250,
    keyword: "らんがく",
    address: "古河市中央町3-11-2",
    description:
      "蘭学者として知られる古河藩家老・鷹見泉石が晩年を過ごした武家屋敷。茅葺きの建物と庭園が江戸の面影を伝える。",
    hours: "9:00〜17:00",
    holiday: "月曜・第4金曜・年末年始",
  },
  {
    id: "bungakukan",
    name: "古河文学館",
    kana: "こがぶんがくかん",
    category: "歴史・文化",
    emoji: "📚",
    color: "#7a4b8f",
    lat: 36.19040,
    lng: 139.69850,
    radius: 250,
    keyword: "れきしぶんがく",
    address: "古河市中央町3-10-21",
    description:
      "歴史小説家・永井路子をはじめ古河ゆかりの文学者を紹介する、茨城県初の文学館。大正ロマン漂う洋館建築も見どころ。",
    hours: "9:00〜17:00",
    holiday: "月曜・第4金曜・年末年始",
  },
  {
    id: "tenkoku",
    name: "篆刻美術館",
    kana: "てんこくびじゅつかん",
    category: "歴史・文化",
    emoji: "🖋️",
    color: "#31567d",
    lat: 36.18970,
    lng: 139.70050,
    radius: 250,
    keyword: "はんこのまち",
    address: "古河市中央町2-4-18",
    description:
      "日本初の篆刻専門美術館。大正9年築の石蔵を改修した建物で、篆刻家・生井子華の遺作などを展示。スタンプラリーと縁の深い「印」の美術館。",
    hours: "9:00〜17:00",
    holiday: "月曜・第4金曜・年末年始",
  },
  {
    id: "nagaimichiko",
    name: "永井路子旧宅",
    kana: "ながいみちこきゅうたく",
    category: "歴史・文化",
    emoji: "🏠",
    color: "#a06522",
    lat: 36.19180,
    lng: 139.70140,
    radius: 200,
    keyword: "ほむらのしろ",
    address: "古河市中央町2-6-52",
    description:
      "直木賞作家・永井路子が少女時代を過ごした江戸時代末期の商家建築。歴史ある「古河宿」の街並みに残る貴重な建物。",
    hours: "10:00〜18:00",
    holiday: "月曜・第4金曜・年末年始",
  },
  {
    id: "sakacho",
    name: "お休み処 坂長",
    kana: "おやすみどころ さかちょう",
    category: "まち歩き",
    emoji: "🍵",
    color: "#3d7a5d",
    lat: 36.19220,
    lng: 139.70200,
    radius: 200,
    keyword: "こがしゅく",
    address: "古河市中央町3-1-39",
    description:
      "古河城の乾門を移築した門構えが目印の観光交流拠点。国の登録有形文化財の店蔵・袖蔵で、お土産と休憩が楽しめる。",
    hours: "10:00〜18:00",
    holiday: "月曜（祝日の場合は翌日）",
  },
  {
    id: "suzumejinja",
    name: "雀神社",
    kana: "すずめじんじゃ",
    category: "神社・仏閣",
    emoji: "⛩️",
    color: "#b03a2e",
    lat: 36.19650,
    lng: 139.69350,
    radius: 250,
    keyword: "ちんじゅさま",
    address: "古河市宮前町4-52",
    description:
      "古河の総鎮守として親しまれる古社。「鎮め(しずめ)の宮」が転じて雀神社になったと伝わる。樹齢数百年の御神木の大欅は圧巻。",
    hours: "参拝自由",
    holiday: "なし",
  },
  {
    id: "shojoji",
    name: "正定寺",
    kana: "しょうじょうじ",
    category: "神社・仏閣",
    emoji: "🙏",
    color: "#6d5b8e",
    lat: 36.18930,
    lng: 139.69590,
    radius: 250,
    keyword: "どいさま",
    address: "古河市大手町7-1",
    description:
      "古河藩主・土井家の菩提寺。東京の土井家下屋敷から移築された黒門や土井利勝の画像など、大名家ゆかりの寺宝が残る。",
    hours: "参拝自由（堂内は要確認）",
    holiday: "なし",
  },
  {
    id: "hasekannon",
    name: "長谷観音",
    kana: "はせかんのん",
    category: "神社・仏閣",
    emoji: "🕊️",
    color: "#2e7d86",
    lat: 36.18850,
    lng: 139.69400,
    radius: 250,
    keyword: "あきばさま",
    address: "古河市長谷町5-1",
    description:
      "明応2年(1493年)、古河公方・足利成氏が古河城の鬼門除けとして勧請したと伝わる観音様。日本三長谷のひとつに数えられる。",
    hours: "9:00〜16:00頃",
    holiday: "なし",
  },
  {
    id: "kubokoen",
    name: "古河公方公園（古河総合公園）",
    kana: "こがくぼうこうえん",
    category: "自然・公園",
    emoji: "🌸",
    color: "#c2547d",
    lat: 36.17480,
    lng: 139.71130,
    radius: 500,
    keyword: "はなももまつり",
    address: "古河市鴻巣399-1",
    description:
      "古河公方・足利成氏の館跡を含む広大な公園。約1,500本の花桃が咲き誇る「古河桃まつり」の会場で、ユネスコのメリナ・メルクーリ国際賞を受賞。",
    hours: "常時開園（駐車場は時間あり）",
    holiday: "なし",
  },
  {
    id: "neblepark",
    name: "ネーブルパーク",
    kana: "ねーぶるぱーく",
    category: "自然・公園",
    emoji: "🐴",
    color: "#4a7d2e",
    lat: 36.15800,
    lng: 139.74400,
    radius: 500,
    keyword: "ちかめいろ",
    address: "古河市駒羽根620",
    description:
      "「関東のへそ」古河にある緑豊かな公園。ポニー乗馬・地下迷路・キャビン宿泊・釣り堀など家族で一日遊べるレジャースポット。",
    hours: "9:00〜17:00（施設により異なる）",
    holiday: "施設により異なる",
  },
  {
    id: "watarase",
    name: "渡良瀬遊水地（古河側）",
    kana: "わたらせゆうすいち",
    category: "自然・公園",
    emoji: "🪁",
    color: "#2f6da8",
    lat: 36.21500,
    lng: 139.68200,
    radius: 800,
    keyword: "らむさーる",
    address: "古河市西町地先ほか",
    description:
      "本州最大級の遊水地でラムサール条約登録湿地。雄大なヨシ原と夕日の絶景は圧巻。サイクリングや熱気球など雄大な自然を満喫できる。",
    hours: "終日（立入可能区域に注意）",
    holiday: "なし",
  },
];

/** スタンプ数に応じた特典ランク */
const REWARDS = [
  {
    count: 3,
    rank: "銅",
    title: "ブロンズ雪華賞",
    icon: "🥉",
    detail: "オリジナル雪華ステッカーをプレゼント（協賛店にて画面提示）",
  },
  {
    count: 6,
    rank: "銀",
    title: "シルバー雪華賞",
    icon: "🥈",
    detail: "古河銘菓の試食券をプレゼント（協賛店にて画面提示）",
  },
  {
    count: 9,
    rank: "金",
    title: "ゴールド雪華賞",
    icon: "🥇",
    detail: "オリジナル篆刻風スタンプグッズをプレゼント",
  },
  {
    count: 12,
    rank: "完全制覇",
    title: "古河公方賞",
    icon: "👑",
    detail: "完全制覇認定証を発行！抽選で古河特産品詰め合わせが当たる",
  },
];
