project_id = "studio-n-lms"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
major_version = 15

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
site_url = "http://localhost:3100"
additional_redirect_urls = ["http://localhost:3100/**"]
enable_signup = false
minimum_password_length = 8

[auth.email]
enable_signup = false
enable_confirmations = false
